name: Apply

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    env:
      TF_VAR_rds_admin: ${{ vars.TF_VAR_RDS_ADMIN }}
      TF_VAR_rds_admin_password: ${{ secrets.TF_VAR_RDS_ADMIN_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t sherman-monarchs:latest .

      - name: Tag Docker image with version
        run: docker tag sherman-monarchs:latest ${{ secrets.AWS_ECR_REPO_URL }}:${VERSION}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPO_URL }}

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ECR_REPO_URL }}:${VERSION}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
